config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # "guest" session
  resources :chat_sessions

  # "Operatoristrator" session
  get '/operator' => 'operator#index'
  namespace :operator do
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'

    resources :chat_sessions, only: %i[create show destroy] do
      member { post :disconnect }
    end
  end

  # assume all visitors are guests
  root 'chat_sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_session.rb
class ChatSession < ApplicationRecord
  include AASM

  before_validation :generate_token
  belongs_to :operator, optional: true

  aasm(:viewer, column: 'viewer_state', namespace: :viewer) do
    state :pending, initial: true
    state :connected
    state :disconnected

    event :connect do
      transitions from: %i[pending disconnected connected], to: :connected
    end

    event :disconnect do
      transitions from: :connected, to: :disconnected
    end
  end

  aasm(:operator, column: 'operator_state', namespace: :operator) do
    state :pending, initial: true
    state :connected
    state :disconnected

    event :connect do
      transitions from: %i[pending disconnected connected], to: :connected
    end

    event :disconnect do
      transitions from: :connected, to: :disconnected
    end
  end

  private

  def generate_token
    self.token = TokenGenerator.generate if self.token.blank?
  end
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_secure_password

  has_many :chat_sessions
end

app/models/session.rb
class Session < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_operator
    if session[:operator_id]
      @current_operator ||= Operator.find(session[:operator_id])
    end
  end #

  helper_method :current_operator

  def prevent_when_signed_in
    if current_operator.present?
      redirect_to operator_path,
                  alert: "Sorry, you can't do that while you're signed in"
    end
  end
end

app/controllers/chat_sessions_controller.rb
class ChatSessionsController < ApplicationController
  before_action :prepare_chat_session, only: %i[new]
  before_action :load_chat_session, only: %i[destroy]
  before_action :prevent_when_signed_in

  def new
    logger.info "[ChatSessions#new] setting session_id to #{@chat_session.id}"
  end

  def destroy
    @chat_session.destroy!
    cookies.delete(:chat_session_id)
    redirect_to root_path
  end

  private

  def load_chat_session
    @chat_session = ChatSession.find_by(id: cookies.encrypted[:chat_session_id])
  end

  def prepare_chat_session
    if cookies.encrypted[:chat_session_id]
      @chat_session =
        ChatSession.find_by(id: cookies.encrypted[:chat_session_id])
    else
      @chat_session = ChatSession.create(active: true)
      cookies.encrypted[:chat_session_id] = @chat_session.id
    end
  end
end

app/controllers/operator/chat_sessions_controller.rb
class Operator::ChatSessionsController < OperatorController
  def index
    @chat_sessions = ChatSession.all
  end

  def show
    @chat_session =
      ChatSession.find_by(id: params[:id], operator: current_operator)

    if @chat_session.nil?
      redirect_to operator_path,
                  alert: 'You are not operating a session with that ID'
      return
    end

    ViewerChannel.broadcast_to(
      @chat_session,
      message: "#{current_operator.email} has connected"
    )
  end

  def create
    logger.info 'Operator::ChatSessionsController create connection'

    @chat_session =
      ChatSession.find_by(
        'token = ? AND (operator_id IS NULL OR operator_id = ?)',
        params[:chat_session][:token],
        current_operator.id
      )

    if @chat_session.present?
      @chat_session.update(operator: current_operator)
      cookies.encrypted[:chat_session_id] = @chat_session.id
      redirect_to operator_chat_session_path(@chat_session)
    else
      redirect_to operator_path,
                  alert: 'Could not find a viewer with that token :('
    end
  end

  def disconnect
    @chat_session =
      ChatSession.find_by(id: params[:id], operator: current_operator)
    @chat_session.update(operator: nil)
    ViewerChannel.broadcast_to(
      @chat_session,
      message: "#{current_operator.email} has disconnected"
    )
    redirect_to operator_path, notice: 'Disconnected from chat session'
  end

  def destroy
    @chat_session.destroy!
    cookies.encrypted.delete(:chat_session_id)
    redirect_to root_path
  end

  private
end

app/controllers/operator/sessions_controller.rb
# Operator authentication
class Operator::SessionsController < OperatorController
  skip_before_action :require_operator!, only: %i[new create]

  def new; end

  def create
    user = Operator.find_by(email: login_params[:email].downcase)
    if user && user.authenticate(login_params[:password])
      session[:operator_id] = user.id.to_s
      redirect_to operator_path, notice: 'Successfully logged in!'
    else
      flash.now.alert = 'Sorry, you do not have access to this resource.'
      render :new
    end
  end

  def destroy
    session.delete(:operator_id)
    redirect_to operator_login_path, notice: 'Logged out!'
  end

  private

  def login_params
    params.require(:operator_login).permit(:email, :password)
  end # delete the saved user_id key/value from the cookie:
end

app/controllers/operator_controller.rb
class OperatorController < ApplicationController
  before_action :require_operator!
  layout 'operator'

  def index; end

  def require_operator!
    if current_operator.nil?
      redirect_to(
        operator_login_path,
        flash: { error: 'You do not have access to this resource' }
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/helpers/connection_status_helper.rb
module ConnectionStatusHelper
  def connection_status
    {
      status: {
        viewer: current_chat_session.viewer_state == 'connected',
        operator: current_chat_session.operator_state == 'connected'
      },
      identity: {
        viewer: current_chat_session.token,
        operator: current_chat_session.operator&.email
      }
    }
  end
end

app/views/chat_sessions/new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="dropdown">
      <%= button_to 'Reset Session', chat_session_path(@chat_session), method: :delete, local: false, class: 'btn btn-danger' %>
    </div>
  </div>
</nav>

<div class="container">
  <div id="signin"></div>
</div>

<script>
  window.SESSION = {
    id: '<%= @chat_session.id %>',
    token: '<%= @chat_session.token %>',
    active: '<%= @chat_session.active.to_s %>',
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cable Session</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/operator.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cable Session</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'operator', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'operator', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'operator/shared/menu' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/operator/chat_sessions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>CHAT SESSION</h1>

      <div id="operator-app"></div>

      <table class="table">
        <tbody>
          <tr>
            <th scope="row">OPERATOR</th>
            <td><%= @chat_session.operator.email %></td>
          </tr>
          <tr>
            <th scope="row">VIEWER</th>
            <td><%= @chat_session.token %></td>
          </tr>
        </tbody>
      </table>

      <%= button_to 'DISCONNECT', disconnect_operator_chat_session_path(@chat_session), method: 'post' %>

      <script>
        window.SESSION = {
          id: '<%= @chat_session.id %>',
          token: '<%= @chat_session.token %>',
          active: '<%= @chat_session.active.to_s %>',
        }
      </script>
    </div>
  </div>
</div>

app/views/operator/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Connect Viewer</h1>

      <%= form_for :chat_session, url: operator_chat_sessions_path, html: { class: 'form-inline' } do |f| %>
        <div class="form-group mb-2">
          <%= f.label :token, class: 'sr-only' %>
          <%= f.text_field :token, class: 'form-control', html_options: { placeholder: 'ENTER CODE' } %>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Connect</button>
      <% end %>
    </div>
  </div>
</div>

app/views/operator/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_operator %>
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= button_to "Sign out", operator_logout_path,
              method: :delete, class: 'dropdown-item' %>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_flash.html.erb
<% unless flash.empty? %>
  <div class="container">
    <% flash.each do |type, msg| %>
      <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
        <%= msg %>
        <button class="close" data-dismiss="alert">x</button>
      </div>
    <% end %>
  </div>
<% end %>